disabled scrollbar
tigerscave/eight-eel-camera-viewer pull request #8
Opened 2023-10-17 10:14 UTC by mre1ght

#7 
<img width="629" alt="スクリーンショット 2023-10-17 19 14 10" src="https://github.com/tigerscave/eight-eel-camera-viewer/assets/129372334/8c263f6d-cec1-4838-89d5-1ba7dcf0f592">

2023-10-19 02:26 UTC, falconkun requested changes
### .gitignore
giboを使いたいです。

### app.py
ping情報を取得する関数が３つありますが、Eelの動きに支障がなければまとめられないでしょうか？
あとTypeをつけたいです。

2023-10-20 08:24 UTC, mre1ght commented
・giboを使って.gitignoreの内容を更新しました。
・確かにコードは汚いです。修正を試みましたが、ダメでした。（threadを別に立てて、やってみましたが、pingを行いませんでした。）
・Typeについて、分かる範囲で付けてみました。

> ### .gitignore
> giboを使いたいです。
> 
> ### app.py
> ping情報を取得する関数が３つありますが、Eelの動きに支障がなければまとめられないでしょうか？ あとTypeをつけたいです。

2023-10-20 09:29 UTC, falconkun requested changes

2023-10-20 09:29 UTC, falconkun commented on app.py
> +def ping_monitoring(host:int) -> str:
引数のTypeは問題ないですが、関数自体のtypeは戻り値がないのでNoneを指定してください。

2023-10-20 09:53 UTC, merged